name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string
      tag:
        description: "Git Tag to checkout"
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15

    # Allow the workflow to push tags/commits back to the repo
    permissions:
      contents: write

    steps:
      # --- Check out main repository (actions/checkout@v4) ---
      - uses: actions/checkout@v4

      # --- Check out sing-box source at the requested tag ---
      - uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          path: box
          ref: ${{ github.event.inputs.tag }}

      # --- Set up Go (actions/setup-go@v5) ---
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      # --- Set up Node (actions/setup-node@v4) ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- Install gomobile toolchain ---
      - name: Setup Gomobile
        run: |
          cd box
          make lib_install
          gomobile init

      # --- Build the iOS xcframework ---
      - name: Build xcframework
        run: |
          cd box
          go run ./cmd/internal/build_libbox -target=ios
          zip -ry ./Libbox.xcframework.zip ./Libbox.xcframework

      # --- Generate SHA‑256 checksum for the archive ---
      - name: Detect checksum
        id: checksum
        shell: bash
        run: |
          CHECKSUM=$(shasum -a 256 box/Libbox.xcframework.zip | awk '{print $1}')
          echo "file_checksum=$CHECKSUM" >> "$GITHUB_ENV"

      # --- Generate SwiftPM manifest that points at the new binary target ---
      - name: Update Package.swift
        shell: bash
        run: |
          cat > Package.swift <<'EOF'
// swift-tools-version: 5.7

import PackageDescription

let package = Package(
  name: "Libbox",
  platforms: [.iOS(.v12)],
  products: [
    .library(name: "Libbox", targets: ["Libbox"]),
  ],
  targets: [
    .binaryTarget(
      name: "Libbox",
      url: "https://github.com/EbrahimTahernejad/sing-box-lib/releases/download/${{ github.event.inputs.version }}/Libbox.xcframework.zip",
      checksum: "${{ env.file_checksum }}"
    )
  ]
)
EOF

      # --- Commit the manifest and tag the commit (stefanzweifel/git-auto-commit-action@v5) ---
      - name: Commit manifest & tag
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Libbox Release ${{ github.event.inputs.version }}"
          commit_user_name: "Ebrahim"
          commit_user_email: "ebrahimtahernejad@gmail.com"
          tagging_message: "${{ github.event.inputs.version }}"
          file_pattern: Package.swift

      # --- Publish GitHub release (softprops/action-gh-release@v2) ---
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          body: "Compiled from source tag: ${{ github.event.inputs.tag }}"
          files: box/Libbox.xcframework.zip
