name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string
      tag:
        description: "Git Tag to checkout"
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15

    # Allow the workflow to push tags/commits back to the repo
    permissions:
      contents: write

    steps:
      # --- Check out main repository (actions/checkout@v4) ---
      - uses: actions/checkout@v4

      # --- Check out sing-box source at the requested tag ---
      - uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          path: box
          ref: ${{ github.event.inputs.tag }}

      # --- Set up Go (actions/setup-go@v5) ---
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      # --- Set up Node (actions/setup-node@v4) ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- Install gomobile toolchain ---
      - name: Setup Gomobile
        run: |
          cd box
          make lib_install
          gomobile init

      # --- Build the iOS xcframework ---
      - name: Build xcframework
        run: |
          cd box
          go run ./cmd/internal/build_libbox -target apple -platform ios,tvos,macos
          zip -ry ./Libbox.xcframework.zip ./Libbox.xcframework

      # --- Generate SHA‑256 checksum for the archive ---
      - name: Detect checksum
        id: checksum
        shell: bash
        run: |
          CHECKSUM=$(shasum -a 256 box/Libbox.xcframework.zip | awk '{print $1}')
          echo "file_checksum=$CHECKSUM" >> "$GITHUB_ENV"

      # --- Generate SwiftPM manifest that points at the new binary target ---
      - name: Update Package.swift
        shell: bash
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Libbox\"," >> Package.swift
          echo "  platforms: [.iOS(.v12)]," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Libbox\", targets: [\"Libbox\"])," >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"Libbox\"," >> Package.swift
          echo "      url: \"https://github.com/EbrahimTahernejad/sing-box-lib/releases/download/${{ github.event.inputs.version }}/Libbox.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.file_checksum }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift

      # --- Commit the manifest and tag the commit (stefanzweifel/git-auto-commit-action@v5) ---
      - name: Commit manifest & tag
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Libbox Release ${{ github.event.inputs.version }}"
          commit_user_name: "Ebrahim"
          commit_user_email: "ebrahimtahernejad@gmail.com"
          tagging_message: "${{ github.event.inputs.version }}"
          file_pattern: Package.swift

      # --- Publish GitHub release (softprops/action-gh-release@v2) ---
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          body: "Compiled from source tag: ${{ github.event.inputs.tag }}"
          files: box/Libbox.xcframework.zip
